version: "3.8"
services:
  node-app:
    build:
      context: ./app
    container_name: app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
